"""add_task_template_groups

Revision ID: 36e95f10a790
Revises: a1b2c3d4e5f6
Create Date: 2026-02-12 01:16:21.991795
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e95f10a790'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('task_template_groups',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('task_templates', sa.Column('group_id', sa.UUID(), nullable=True))
    op.create_index('ix_task_templates_group_id', 'task_templates', ['group_id'])
    op.create_foreign_key('fk_task_templates_group_id', 'task_templates', 'task_template_groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_task_templates_group_id', 'task_templates', type_='foreignkey')
    op.drop_index('ix_task_templates_group_id', table_name='task_templates')
    op.drop_column('task_templates', 'group_id')
    op.drop_table('task_template_groups')
    # ### end Alembic commands ###
