"""add_github_pats_table

Revision ID: 9e2e02899589
Revises: 89b0d191b4f8
Create Date: 2026-02-16 04:28:25.282810
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e2e02899589'
down_revision: Union[str, None] = '89b0d191b4f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('github_pats',
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('token_encrypted', sa.String(), nullable=False),
    sa.Column('github_username', sa.String(), nullable=False),
    sa.Column('github_avatar_url', sa.String(), nullable=True),
    sa.Column('github_user_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('scopes', sa.String(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('github_pats')
    # ### end Alembic commands ###
