"""add_token_hash_to_github_pats

Revision ID: ad1616c34a2b
Revises: 9e2e02899589
Create Date: 2026-02-16 04:48:10.301707
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad1616c34a2b'
down_revision: Union[str, None] = '9e2e02899589'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM github_pats")
    op.add_column('github_pats', sa.Column('token_hash', sa.String(), nullable=False))
    op.create_unique_constraint('uq_github_pats_user_token', 'github_pats', ['created_by', 'token_hash'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_github_pats_user_token', 'github_pats', type_='unique')
    op.drop_column('github_pats', 'token_hash')
    # ### end Alembic commands ###
