"""add_engineer_evaluations_table

Revision ID: cf6ed5f4332d
Revises: 36e95f10a790
Create Date: 2026-02-12 13:37:45.601269
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf6ed5f4332d'
down_revision: Union[str, None] = '36e95f10a790'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineer_evaluations',
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('evaluated_by', sa.UUID(), nullable=True),
    sa.Column('evaluation_period', sa.String(), nullable=False),
    sa.Column('code_quality', sa.Float(), nullable=False),
    sa.Column('architecture', sa.Float(), nullable=False),
    sa.Column('ai_skills', sa.Float(), nullable=False),
    sa.Column('debugging', sa.Float(), nullable=False),
    sa.Column('understanding_requirements', sa.Float(), nullable=False),
    sa.Column('ui_ux_design', sa.Float(), nullable=False),
    sa.Column('communication', sa.Float(), nullable=False),
    sa.Column('team_behavior', sa.Float(), nullable=False),
    sa.Column('reliability', sa.Float(), nullable=False),
    sa.Column('ownership', sa.Float(), nullable=False),
    sa.Column('business_impact', sa.Float(), nullable=False),
    sa.Column('leadership', sa.Float(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evaluated_by'], ['profiles.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('engineer_evaluations')
    # ### end Alembic commands ###
