"""Generate downloadable .docx reports matching the daily briefing format."""

import io
import json
import logging
from datetime import datetime, timezone
from uuid import UUID

from docx import Document
from docx.shared import Pt, RGBColor
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement
from sqlalchemy.ext.asyncio import AsyncSession

from apps.api.services.llm_config import get_llm_config
from apps.api.services.report_service import ReportService

logger = logging.getLogger(__name__)


def _add_hyperlink(paragraph, url: str, text: str) -> None:
    """Add a clickable hyperlink to a paragraph."""
    part = paragraph.part
    r_id = part.relate_to(url, "http://schemas.openxmlformats.org/officeDocument/2006/relationships/hyperlink", is_external=True)
    hyperlink = OxmlElement("w:hyperlink")
    hyperlink.set(qn("r:id"), r_id)
    new_run = OxmlElement("w:r")
    r_pr = OxmlElement("w:rPr")
    c = OxmlElement("w:color")
    c.set(qn("w:val"), "0563C1")
    r_pr.append(c)
    u = OxmlElement("w:u")
    u.set(qn("w:val"), "single")
    r_pr.append(u)
    sz = OxmlElement("w:sz")
    sz.set(qn("w:val"), "18")
    r_pr.append(sz)
    new_run.append(r_pr)
    new_run.text = text
    hyperlink.append(new_run)
    paragraph._p.append(hyperlink)


class ReportDocumentService:
    """Generate a Word document report for selected projects."""

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    async def generate(self, product_ids: list[UUID]) -> io.BytesIO:
        """Build a .docx report for the given product IDs."""
        svc = ReportService(self.session)
        summary = await svc.get_summary()

        # Filter to selected projects
        projects = [p for p in summary["projects"] if p["product_id"] in product_ids]
        if not projects:
            projects = summary["projects"]

        pids = [p["product_id"] for p in projects]
        task_data = await svc.get_tasks_for_report(pids)
        ai_summary = await self._generate_executive_summary(projects, task_data)

        doc = Document()
        self._set_default_font(doc)
        self._add_title(doc)
        self._add_executive_summary(doc, ai_summary)
        self._add_project_updates(doc, projects, task_data)
        self._add_portfolio_table(doc, projects, task_data)

        buf = io.BytesIO()
        doc.save(buf)
        buf.seek(0)
        return buf

    # ------------------------------------------------------------------
    # Document sections
    # ------------------------------------------------------------------

    @staticmethod
    def _set_default_font(doc: Document) -> None:
        style = doc.styles["Normal"]
        font = style.font
        font.name = "Calibri"
        font.size = Pt(10)

    @staticmethod
    def _add_title(doc: Document) -> None:
        import os
        from docx.shared import Inches

        # Logo + "Mizan OS" top-right
        branding = doc.add_paragraph()
        branding.alignment = WD_ALIGN_PARAGRAPH.RIGHT
        logo_path = os.path.join(os.path.dirname(__file__), "mizan_logo.png")
        if os.path.exists(logo_path):
            run = branding.add_run()
            run.add_picture(logo_path, width=Inches(0.28))
        run = branding.add_run("  Mizan OS")
        run.bold = True
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(80, 80, 80)

        # Footer with page number + "Generated by Mizan PM Tool"
        from docx.oxml.ns import qn
        from docx.oxml import OxmlElement
        sectPr = doc.sections[0]._sectPr
        footer = OxmlElement("w:footerReference")
        # Use default footer via section properties
        for section in doc.sections:
            footer_obj = section.footer
            footer_obj.is_linked_to_previous = False
            fp = footer_obj.paragraphs[0] if footer_obj.paragraphs else footer_obj.add_paragraph()
            fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
            # Page number field
            run = fp.add_run("Page ")
            run.font.size = Pt(8)
            run.font.color.rgb = RGBColor(150, 150, 150)
            fld_char1 = OxmlElement("w:fldChar")
            fld_char1.set(qn("w:fldCharType"), "begin")
            run_pg = fp.add_run()
            run_pg._r.append(fld_char1)
            instr = OxmlElement("w:instrText")
            instr.set(qn("xml:space"), "preserve")
            instr.text = " PAGE "
            run_pg2 = fp.add_run()
            run_pg2._r.append(instr)
            fld_char2 = OxmlElement("w:fldChar")
            fld_char2.set(qn("w:fldCharType"), "end")
            run_pg3 = fp.add_run()
            run_pg3._r.append(fld_char2)
            # Second line
            fp2 = footer_obj.add_paragraph()
            fp2.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run2 = fp2.add_run("Generated by Mizan PM Tool")
            run2.italic = True
            run2.font.size = Pt(7)
            run2.font.color.rgb = RGBColor(170, 170, 170)

        title = doc.add_paragraph()
        title.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = title.add_run("PROJECT STATUS UPDATE")
        run.bold = True
        run.font.size = Pt(18)
        run.font.color.rgb = RGBColor(0, 0, 0)

        date_str = datetime.now(timezone.utc).strftime("Daily Briefing - %d %B %Y")
        sub = doc.add_paragraph()
        run = sub.add_run(date_str)
        run.font.size = Pt(11)
        run.font.color.rgb = RGBColor(100, 100, 100)
        doc.add_paragraph()

    @staticmethod
    def _add_executive_summary(doc: Document, text: str) -> None:
        heading = doc.add_paragraph()
        run = heading.add_run("Executive Summary")
        run.bold = True
        run.font.size = Pt(14)

        p = doc.add_paragraph()
        run = p.add_run(text)
        run.font.size = Pt(10)
        doc.add_paragraph()

    @staticmethod
    def _add_project_updates(
        doc: Document, projects: list[dict], task_data: dict,
    ) -> None:
        heading = doc.add_paragraph()
        run = heading.add_run("Project Updates")
        run.bold = True
        run.font.size = Pt(14)

        for proj in projects:
            pid = proj["product_id"]
            name = proj["product_name"]
            stage = proj.get("stage") or "N/A"
            pm = proj.get("pm_name") or "-"
            dev = proj.get("dev_name") or "-"
            td = task_data.get(pid, {})

            # Project header
            ph = doc.add_paragraph()
            run = ph.add_run(f"{name}  ")
            run.bold = True
            run.font.size = Pt(12)
            run = ph.add_run(f"{stage.upper()}  ")
            run.bold = True
            run.font.size = Pt(10)
            run.font.color.rgb = RGBColor(0, 128, 0)
            run = ph.add_run(f"PM: {pm}  Dev: {dev}")
            run.font.size = Pt(10)
            run.font.color.rgb = RGBColor(100, 100, 100)

            # Ready for GTM if Deployment
            if (stage or "").upper() == "DEPLOYMENT":
                gtm = doc.add_paragraph()
                run = gtm.add_run("Ready for GTM")
                run.bold = True
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor(0, 150, 0)

            # Task summary line
            summary_line = td.get("summary_line", "")
            if summary_line:
                sp = doc.add_paragraph()
                run = sp.add_run(summary_line)
                run.bold = True
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor(80, 80, 80)

            # Non-done tasks: bullet + title + small tag at end, no dev name
            non_done = td.get("non_done_tasks", [])
            for t in non_done:
                is_overdue = t.get("is_overdue", False)
                status_raw = (t.get("status") or "unknown").upper()
                tag = "OVERDUE" if is_overdue else status_raw
                title = t.get("title", "")[:65]

                tp = doc.add_paragraph(style="List Bullet")
                run = tp.add_run(title)
                run.font.size = Pt(9)
                run = tp.add_run(f"  [{tag}]")
                run.font.size = Pt(7)
                if is_overdue:
                    run.font.color.rgb = RGBColor(200, 0, 0)
                elif status_raw in ("IN_PROGRESS", "IN_REVIEW", "REVIEW"):
                    run.font.color.rgb = RGBColor(180, 100, 0)
                else:
                    run.font.color.rgb = RGBColor(130, 130, 130)

            # Explore this project
            project_links = td.get("links", [])
            live_url = proj.get("live_url")
            dash_url = proj.get("dashboard_url")
            if project_links or live_url or dash_url:
                lp = doc.add_paragraph()
                run = lp.add_run("Explore this project:")
                run.bold = True
                run.font.size = Pt(9)
                run.font.color.rgb = RGBColor(80, 80, 80)
                for pl in project_links:
                    link_p = doc.add_paragraph()
                    run = link_p.add_run(f"  {pl.get('name', 'Link')}: ")
                    run.font.size = Pt(9)
                    _add_hyperlink(link_p, pl.get("url", ""), pl.get("url", ""))
                if live_url:
                    link_p = doc.add_paragraph()
                    run = link_p.add_run("  Live: ")
                    run.font.size = Pt(9)
                    _add_hyperlink(link_p, live_url, live_url)
                if dash_url:
                    link_p = doc.add_paragraph()
                    run = link_p.add_run("  Dashboard: ")
                    run.font.size = Pt(9)
                    _add_hyperlink(link_p, dash_url, dash_url)

            doc.add_paragraph()

    @staticmethod
    def _add_portfolio_table(doc: Document, projects: list[dict], task_data: dict | None = None) -> None:
        heading = doc.add_paragraph()
        run = heading.add_run("Portfolio Directory")
        run.bold = True
        run.font.size = Pt(14)

        sub = doc.add_paragraph()
        run = sub.add_run("Quick reference for all projects.")
        run.font.size = Pt(10)
        run.italic = True
        run.font.color.rgb = RGBColor(100, 100, 100)

        headers = ["Project", "Status", "PM", "Dev", "Live Link", "Dashboard / Dev"]
        table = doc.add_table(rows=1, cols=len(headers))
        table.style = "Light Grid Accent 1"

        for i, h in enumerate(headers):
            cell = table.rows[0].cells[i]
            cell.text = h
            for run in cell.paragraphs[0].runs:
                run.bold = True
                run.font.size = Pt(8)

        for proj in projects:
            pid = proj["product_id"]
            td = (task_data or {}).get(pid, {})
            project_links = td.get("links", [])

            # Separate live link vs other links
            live_link = next((pl for pl in project_links if pl.get("name", "").lower() == "live"), None)
            other_links = [pl for pl in project_links if pl.get("name", "").lower() != "live"]

            row = table.add_row()
            cells = row.cells
            cells[0].text = proj["product_name"]
            cells[1].text = proj.get("stage") or "-"
            cells[2].text = proj.get("pm_name") or "-"
            cells[3].text = proj.get("dev_name") or "-"

            # Live Link — from project_links "Live" or environment live_url
            live_url = live_link["url"] if live_link else proj.get("live_url")
            if live_url:
                cells[4].text = ""
                p = cells[4].paragraphs[0]
                _add_hyperlink(p, live_url, _shorten_url(live_url))
            else:
                cells[4].text = "-"

            # Dashboard / Dev — all other project links with labels
            dash_url = proj.get("dashboard_url")
            if other_links:
                cells[5].text = ""
                p = cells[5].paragraphs[0]
                first = other_links[0]
                label = first.get("name", "Link")
                run = p.add_run(f"[{label}] ")
                run.font.size = Pt(7)
                run.font.color.rgb = RGBColor(100, 100, 100)
                _add_hyperlink(p, first["url"], _shorten_url(first["url"]))
            elif dash_url:
                cells[5].text = ""
                p = cells[5].paragraphs[0]
                _add_hyperlink(p, dash_url, _shorten_url(dash_url))
            else:
                cells[5].text = "-"

            for cell in cells:
                for p in cell.paragraphs:
                    for run in p.runs:
                        run.font.size = Pt(8)

    # ------------------------------------------------------------------
    # AI generation
    # ------------------------------------------------------------------

    async def _generate_executive_summary(self, projects: list[dict], task_data: dict | None = None) -> str:
        lines = []
        for p in projects:
            pid = p["product_id"]
            td = (task_data or {}).get(pid, {})
            summary = td.get("summary_line", f"{p['completed_tasks']}/{p['total_tasks']} tasks")
            non_done_count = len(td.get("non_done_tasks", []))
            lines.append(
                f"- {p['product_name']} ({p.get('stage', 'N/A')}): "
                f"{summary}, {p.get('total_commits', 0)} commits, "
                f"{non_done_count} pending tasks"
            )
        context = "\n".join(lines)

        prompt = (
            "Write a concise executive summary (1 paragraph, 4-6 sentences) for a "
            "daily project status briefing. Summarize the key highlights across these "
            "projects. Be specific about project names, task completion, and pending items. "
            "Mention projects with overdue or blocked tasks. "
            "No markdown, no bullet points - just flowing prose.\n\n"
            f"Projects:\n{context}"
        )
        return await self._call_llm(prompt)

    async def _call_llm(self, prompt: str) -> str:
        import openai

        config = await get_llm_config(self.session)
        client = openai.AsyncOpenAI(api_key=config.api_key, base_url=config.base_url)
        response = await client.chat.completions.create(
            model=config.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5,
            max_tokens=2048,
        )
        return response.choices[0].message.content or ""


def _shorten_url(url: str) -> str:
    """Remove protocol prefix for display."""
    return url.replace("https://", "").replace("http://", "").rstrip("/")
