"""Generate downloadable PDF reports matching the daily briefing format."""

import io
import json
import logging
from datetime import datetime, timezone
from uuid import UUID

from fpdf import FPDF
from sqlalchemy.ext.asyncio import AsyncSession

from apps.api.services.llm_config import get_llm_config
from apps.api.services.report_service import ReportService

logger = logging.getLogger(__name__)


class _ReportPDF(FPDF):
    """Custom FPDF subclass with report styling helpers."""

    def header(self) -> None:
        pass

    def footer(self) -> None:
        self.set_y(-18)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 5, f"Page {self.page_no()}/{{nb}}", align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "I", 7)
        self.set_text_color(170, 170, 170)
        self.cell(0, 4, "Generated by Mizan PM Tool", align="C")


class ReportPDFService:
    """Generate a PDF report for selected projects."""

    def __init__(self, session: AsyncSession) -> None:
        self.session = session

    async def generate(self, product_ids: list[UUID], report_type: str = "general") -> io.BytesIO:
        """Build a PDF report for the given product IDs."""
        svc = ReportService(self.session)
        summary = await svc.get_summary()

        projects = [p for p in summary["projects"] if p["product_id"] in product_ids]
        if not projects:
            projects = summary["projects"]

        pids = [p["product_id"] for p in projects]
        is_bugs = report_type == "bugs"
        task_data = await svc.get_bugs_for_report(pids) if is_bugs else await svc.get_tasks_for_report(pids)
        ai_summary = await self._generate_executive_summary(projects, task_data)

        pdf = _ReportPDF()
        pdf.alias_nb_pages()
        pdf.set_auto_page_break(auto=True, margin=20)
        pdf.add_page()

        self._add_title(pdf, is_bugs=is_bugs)
        self._add_executive_summary(pdf, ai_summary)
        self._add_project_updates(pdf, projects, task_data, is_bugs=is_bugs)
        self._add_portfolio_table(pdf, projects, task_data)

        buf = io.BytesIO()
        pdf.output(buf)
        buf.seek(0)
        return buf

    # ------------------------------------------------------------------
    # PDF sections
    # ------------------------------------------------------------------

    @staticmethod
    def _add_title(pdf: _ReportPDF, is_bugs: bool = False) -> None:
        import os
        # Logo + "Mizan OS" top-right
        logo_path = os.path.join(os.path.dirname(__file__), "mizan_logo.png")
        y = pdf.get_y()
        if os.path.exists(logo_path):
            pdf.image(logo_path, x=pdf.w - pdf.r_margin - 28, y=y, w=8)
        pdf.set_font("Helvetica", "B", 9)
        pdf.set_text_color(80, 80, 80)
        pdf.set_xy(pdf.w - pdf.r_margin - 19, y + 1)
        pdf.cell(19, 5, "Mizan OS", align="L")
        pdf.set_xy(pdf.l_margin, y + 10)

        pdf.set_font("Helvetica", "B", 20)
        pdf.set_text_color(0, 0, 0)
        title = "BUG STATUS REPORT" if is_bugs else "PROJECT STATUS UPDATE"
        pdf.cell(0, 12, title, new_x="LMARGIN", new_y="NEXT")

        date_str = datetime.now(timezone.utc).strftime("Bug Report - %d %B %Y" if is_bugs else "Daily Briefing - %d %B %Y")
        pdf.set_font("Helvetica", "", 11)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 8, date_str, new_x="LMARGIN", new_y="NEXT")

        pdf.set_draw_color(200, 200, 200)
        pdf.line(pdf.l_margin, pdf.get_y() + 2, pdf.w - pdf.r_margin, pdf.get_y() + 2)
        pdf.ln(8)

    @staticmethod
    def _add_executive_summary(pdf: _ReportPDF, text: str) -> None:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(31, 73, 125)
        pdf.cell(0, 10, "Executive Summary", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(0, 0, 0)
        pdf.multi_cell(0, 5, text)
        pdf.ln(6)

    @staticmethod
    def _add_project_updates(
        pdf: _ReportPDF, projects: list[dict], task_data: dict, is_bugs: bool = False,
    ) -> None:
        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(31, 73, 125)
        section_title = "Bug Reports by Project" if is_bugs else "Project Updates"
        pdf.cell(0, 10, section_title, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        for proj in projects:
            pid = proj["product_id"]
            name = proj["product_name"]
            stage = (proj.get("stage") or "N/A").upper()
            pm = proj.get("pm_name") or "-"
            # Show all dev names if multiple, otherwise single dev
            dev_names = proj.get("dev_names", [])
            dev = ", ".join(dev_names) if dev_names else (proj.get("dev_name") or "-")
            td = task_data.get(pid, {})

            if pdf.get_y() > pdf.h - 50:
                pdf.add_page()

            # Project name + stage + PM/Dev
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(0, 0, 0)
            pdf.cell(pdf.get_string_width(name) + 2, 7, name)
            pdf.set_font("Helvetica", "B", 9)
            _stage_color(pdf, stage)
            pdf.cell(pdf.get_string_width(stage) + 4, 7, stage)
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(100, 100, 100)
            pdf.cell(0, 7, f"  PM: {pm}  Dev: {dev}", new_x="LMARGIN", new_y="NEXT")

            # Ready for GTM line if stage is Deployment
            if stage == "DEPLOYMENT":
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(0, 150, 0)
                pdf.cell(0, 6, "Ready for GTM", new_x="LMARGIN", new_y="NEXT")

            # Task summary line
            summary_line = td.get("summary_line", "")
            if summary_line:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(60, 60, 60)
                pdf.cell(0, 6, _sanitize_text(summary_line), new_x="LMARGIN", new_y="NEXT")

            # In-progress + done-today tasks grouped by milestone
            milestones = td.get("milestones", {})
            for milestone_name, tasks in milestones.items():
                if not tasks:
                    continue

                if pdf.get_y() > pdf.h - 25:
                    pdf.add_page()

                # Milestone heading
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(80, 80, 140)
                pdf.cell(0, 6, f"{_sanitize_text(milestone_name)}:", new_x="LMARGIN", new_y="NEXT")

                # Tasks under this milestone
                for t in tasks:
                    if pdf.get_y() > pdf.h - 20:
                        pdf.add_page()
                    tag = t.get("tag", (t.get("status") or "unknown").upper())
                    title = _sanitize_text(t.get("title", ""))[:65]
                    show_assignee = t.get("show_assignee", False)
                    assignee_name = t.get("assignee_name")

                    pdf.set_x(pdf.l_margin + 6)
                    pdf.set_font("Helvetica", "", 8)
                    pdf.set_text_color(0, 0, 0)
                    pdf.cell(4, 5, "*")
                    pdf.cell(0, 5, f" {title}", new_x="END")
                    # Add assignee name if project has multiple assignees
                    if show_assignee and assignee_name and assignee_name != "Unassigned":
                        pdf.set_font("Helvetica", "", 6)
                        pdf.set_text_color(80, 80, 80)
                        pdf.cell(0, 5, f"  @{_sanitize_text(assignee_name)}", new_x="END")
                    pdf.set_font("Helvetica", "", 6)
                    if tag == "DONE TODAY":
                        pdf.set_text_color(0, 150, 0)
                    elif tag in ("IN PROGRESS", "IN REVIEW", "REVIEW"):
                        pdf.set_text_color(180, 100, 0)
                    else:
                        pdf.set_text_color(130, 130, 130)
                    pdf.cell(0, 5, f"  [{tag}]", new_x="LMARGIN", new_y="NEXT")

            # Explore this project (same size as task summary)
            project_links = td.get("links", [])
            live_url = proj.get("live_url")
            dash_url = proj.get("dashboard_url")
            if project_links or live_url or dash_url:
                pdf.set_font("Helvetica", "B", 9)
                pdf.set_text_color(60, 60, 60)
                pdf.cell(0, 6, "Explore this project:", new_x="LMARGIN", new_y="NEXT")
                pdf.set_font("Helvetica", "", 8)
                for pl in project_links:
                    pdf.set_x(pdf.l_margin + 8)
                    pdf.set_text_color(60, 60, 60)
                    label = _sanitize_text(pl.get("name", "Link"))
                    pdf.cell(pdf.get_string_width(f"{label}: ") + 1, 5, f"{label}: ")
                    pdf.set_text_color(5, 99, 193)
                    pdf.cell(0, 5, _shorten(pl.get("url", "")), new_x="LMARGIN", new_y="NEXT", link=pl.get("url", ""))
                if live_url:
                    pdf.set_x(pdf.l_margin + 8)
                    pdf.set_text_color(60, 60, 60)
                    pdf.cell(pdf.get_string_width("Live: ") + 1, 5, "Live: ")
                    pdf.set_text_color(5, 99, 193)
                    pdf.cell(0, 5, _shorten(live_url), new_x="LMARGIN", new_y="NEXT", link=live_url)
                if dash_url:
                    pdf.set_x(pdf.l_margin + 8)
                    pdf.set_text_color(60, 60, 60)
                    pdf.cell(pdf.get_string_width("Dashboard: ") + 1, 5, "Dashboard: ")
                    pdf.set_text_color(5, 99, 193)
                    pdf.cell(0, 5, _shorten(dash_url), new_x="LMARGIN", new_y="NEXT", link=dash_url)

            pdf.ln(6)

    @staticmethod
    def _add_portfolio_table(pdf: _ReportPDF, projects: list[dict], task_data: dict | None = None) -> None:
        if pdf.get_y() > pdf.h - 60:
            pdf.add_page()

        pdf.set_font("Helvetica", "B", 14)
        pdf.set_text_color(31, 73, 125)
        pdf.cell(0, 10, "Portfolio Directory", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "I", 9)
        pdf.set_text_color(100, 100, 100)
        pdf.cell(0, 6, "Quick reference for all projects.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        headers = ["Project", "Status", "PM", "Dev", "Live Link", "Dashboard / Dev"]
        col_w = [30, 20, 26, 26, 44, 44]
        row_h = 7

        pdf.set_font("Helvetica", "B", 7)
        pdf.set_fill_color(220, 230, 241)
        pdf.set_text_color(0, 0, 0)
        for i, h in enumerate(headers):
            pdf.cell(col_w[i], row_h, h, border=1, fill=True)
        pdf.ln(row_h)

        pdf.set_font("Helvetica", "", 7)
        for idx, proj in enumerate(projects):
            fill = idx % 2 == 1
            if fill:
                pdf.set_fill_color(245, 245, 245)

            if pdf.get_y() > pdf.h - 20:
                pdf.add_page()
                pdf.set_font("Helvetica", "B", 7)
                pdf.set_fill_color(220, 230, 241)
                for i, h in enumerate(headers):
                    pdf.cell(col_w[i], row_h, h, border=1, fill=True)
                pdf.ln(row_h)
                pdf.set_font("Helvetica", "", 7)

            pid = proj["product_id"]
            td = (task_data or {}).get(pid, {})
            project_links = td.get("links", [])

            # Separate live link vs other links
            live_link = next((pl for pl in project_links if pl.get("name", "").lower() == "live"), None)
            other_links = [pl for pl in project_links if pl.get("name", "").lower() != "live"]

            # Show all dev names if multiple
            dev_names = proj.get("dev_names", [])
            dev_display = ", ".join(dev_names) if dev_names else (proj.get("dev_name") or "-")

            pdf.set_text_color(0, 0, 0)
            pdf.cell(col_w[0], row_h, proj["product_name"][:18], border=1, fill=fill)
            pdf.cell(col_w[1], row_h, (proj.get("stage") or "-")[:12], border=1, fill=fill)
            pdf.cell(col_w[2], row_h, (proj.get("pm_name") or "-")[:16], border=1, fill=fill)
            pdf.cell(col_w[3], row_h, dev_display[:16], border=1, fill=fill)

            # Live Link column — from project_links "Live" or environment live_url
            live_url = live_link["url"] if live_link else proj.get("live_url")
            if live_url:
                pdf.set_text_color(5, 99, 193)
                pdf.cell(col_w[4], row_h, _shorten(live_url)[:26], border=1, fill=fill, link=live_url)
            else:
                pdf.cell(col_w[4], row_h, "-", border=1, fill=fill)

            # Dashboard / Dev — all other project links (Railway, Dashboard, Admin, etc.)
            dash_url = proj.get("dashboard_url")
            if other_links:
                first = other_links[0]
                label = first.get("name", "")[:8]
                url = first["url"]
                pdf.set_text_color(5, 99, 193)
                display = f"[{label}] {_shorten(url)}"[:26]
                pdf.cell(col_w[5], row_h, display, border=1, fill=fill, link=url)
            elif dash_url:
                pdf.set_text_color(5, 99, 193)
                pdf.cell(col_w[5], row_h, _shorten(dash_url)[:26], border=1, fill=fill, link=dash_url)
            else:
                pdf.set_text_color(0, 0, 0)
                pdf.cell(col_w[5], row_h, "-", border=1, fill=fill)

            pdf.ln(row_h)

    # ------------------------------------------------------------------
    # AI generation (reuses same prompts as docx service)
    # ------------------------------------------------------------------

    async def _generate_executive_summary(self, projects: list[dict], task_data: dict | None = None) -> str:
        lines = []
        for p in projects:
            pid = p["product_id"]
            td = (task_data or {}).get(pid, {})
            summary = td.get("summary_line", f"{p['completed_tasks']}/{p['total_tasks']} tasks")
            non_done_count = len(td.get("non_done_tasks", []))
            lines.append(
                f"- {p['product_name']} ({p.get('stage', 'N/A')}): "
                f"{summary}, {p.get('total_commits', 0)} commits, "
                f"{non_done_count} pending tasks"
            )
        context = "\n".join(lines)
        prompt = (
            "Write a concise executive summary (1 paragraph, 3-4 sentences) for a "
            "project status briefing. Mention project names, completion, and pending items. "
            "No markdown, no bullets - flowing prose.\n\n"
            f"Projects:\n{context}"
        )
        return _sanitize_text(await self._call_llm(prompt))

    async def _call_llm(self, prompt: str) -> str:
        import openai
        config = await get_llm_config(self.session)
        client = openai.AsyncOpenAI(api_key=config.api_key, base_url=config.base_url)
        response = await client.chat.completions.create(
            model=config.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.5,
            max_tokens=512,
        )
        raw = response.choices[0].message.content or ""
        return _sanitize_text(raw)


def _sanitize_text(text: str) -> str:
    """Replace unicode characters that fpdf2 Helvetica can't render."""
    replacements = {
        "\u2014": "-", "\u2013": "-", "\u2018": "'", "\u2019": "'",
        "\u201c": '"', "\u201d": '"', "\u2022": "*", "\u2026": "...",
        "\u00a0": " ",
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    return text


def _shorten(url: str) -> str:
    """Remove protocol prefix for display."""
    return url.replace("https://", "").replace("http://", "").rstrip("/")


def _stage_color(pdf: _ReportPDF, stage: str) -> None:
    """Set text color based on stage."""
    s = stage.lower()
    if s in ("live", "production", "complete"):
        pdf.set_text_color(0, 128, 0)
    elif s in ("ready for gtm", "deployment"):
        pdf.set_text_color(0, 100, 0)
    elif s in ("qa", "testing"):
        pdf.set_text_color(200, 150, 0)
    elif s in ("development", "in dev"):
        pdf.set_text_color(31, 73, 125)
    elif s == "intake":
        pdf.set_text_color(200, 130, 0)
    else:
        pdf.set_text_color(100, 100, 100)
