"""Product Hunt knowledge base entries — the full GTM playbook.

Each tuple is (title, content). All entries use category="gtm", entry_type="text".
Content uses GitHub-flavored markdown for rich rendering.
"""

# fmt: off
PH_KNOWLEDGE_ENTRIES: list[tuple[str, str]] = [
    (
        "What Is Product Hunt?",
        "Product Hunt is the internet's most influential product launch platform. Every day, makers "
        "submit their products to be discovered, upvoted, and discussed by a community of early "
        "adopters, investors, journalists, and fellow founders.\n\n"
        "## Why It Matters for Startups\n\n"
        "1. **Traffic & Distribution** — A top-5 launch can drive 5,000-20,000 unique visitors in 24 "
        "hours, with a long tail of discovery traffic for weeks after.\n\n"
        "2. **SEO Authority** — Product Hunt has a Domain Rating of 91. A backlink from PH is one of "
        "the highest-quality backlinks a startup can earn organically.\n\n"
        "3. **Social Proof** — 'Featured on Product Hunt' badges, ranking screenshots, and community "
        "endorsements serve as credibility signals for investors, press, and potential customers.\n\n"
        "4. **Press & Partnerships** — Tech journalists actively monitor PH for story leads. A strong "
        "launch creates a news hook that makes outreach dramatically easier.\n\n"
        "5. **User Feedback** — The PH community gives honest, constructive feedback. Many makers "
        "discover critical UX issues or positioning problems during their launch that they would "
        "not have found otherwise.\n\n"
        "6. **Investor Signal** — VCs and angels browse PH daily. A well-executed launch demonstrates "
        "execution ability, market interest, and community traction."
    ),
    (
        "How the Ranking Algorithm Works",
        "Product Hunt's ranking algorithm determines which products appear at the top of the daily "
        "leaderboard. Understanding how it works is critical because the difference between #1 and "
        "#10 can be 5-10x in traffic.\n\n"
        "## Key Ranking Factors\n\n"
        "1. **Vote Quality Over Quantity** — Not all upvotes are equal. Votes from established PH "
        "members with history (comments, upvotes, maker activity) carry significantly more weight "
        "than votes from new or inactive accounts.\n\n"
        "2. **Velocity Matters** — The algorithm rewards sustained momentum throughout the 24-hour "
        "window. A burst of 200 votes in hour 1 followed by silence is worse than steady "
        "engagement spread across the full day.\n\n"
        "3. **Engagement Depth** — Comments, replies, and discussions signal genuine interest. A "
        "product with 100 upvotes and 50 thoughtful comments often outranks one with 200 upvotes "
        "and 5 comments.\n\n"
        "4. **Anti-Gaming Measures** — PH actively penalizes coordinated voting from the same IP "
        "ranges, new accounts created for voting, and suspicious patterns like all votes arriving "
        "within the same 10-minute window.\n\n"
        "> [!tip] Instead of asking people to 'upvote', ask them to 'check it out and share feedback.' "
        "Direct upvote solicitation can trigger penalties.\n\n"
        "5. **The 24-Hour Window** — Products compete within a single calendar day (Pacific Time). "
        "The clock starts at 12:01 AM PST and ends at 11:59 PM PST. This is why launching at "
        "exactly 12:01 AM gives you the maximum competitive window."
    ),
    (
        "The Role of a Hunter",
        "A 'Hunter' on Product Hunt is the person who submits (hunts) a product. While makers can "
        "self-submit, having an established hunter provides significant advantages.\n\n"
        "## What Hunters Do\n\n"
        "- Submit the product to PH with optimized title, tagline, and description\n"
        "- Their followers get notified when they hunt a new product\n"
        "- Top hunters have thousands of followers, giving instant visibility\n"
        "- They lend credibility — their endorsement signals quality to the community\n\n"
        "## Why Top Hunters Matter\n\n"
        "A hunter with 10,000+ followers means 10,000+ people see your product in their feed "
        "on launch day, before any organic discovery. This early visibility boost creates the "
        "velocity the algorithm rewards.\n\n"
        "## Outreach Strategy\n\n"
        "1. Start **2-3 weeks** before your target launch date\n"
        "2. Research hunters who have hunted products in your category\n"
        "3. Send a personalized message explaining your product and why it matters\n"
        "4. Offer a demo or early access — let them experience the product firsthand\n"
        "5. Do not ask multiple hunters simultaneously; it creates confusion\n"
        "6. If a top hunter declines, move down your list — any established hunter is better "
        "than self-hunting\n\n"
        "## Self-Hunting\n\n"
        "If you cannot secure a hunter, self-hunting is perfectly valid. Many successful "
        "launches are self-hunted. The key is to compensate with stronger community engagement "
        "and outreach."
    ),
    (
        "The Coming Soon Page",
        "Product Hunt's 'Coming Soon' feature lets you build anticipation before your official "
        "launch. It functions as a pre-launch teaser page within the PH ecosystem.\n\n"
        "## Key Elements\n\n"
        "- **Desktop Banner:** 1:2 aspect ratio (e.g., 1270x640px)\n"
        "- **Mobile Banner:** 1:1 aspect ratio (e.g., 640x640px)\n"
        "- **Short Description:** Tease the product without giving everything away\n"
        "- **Email Collection:** Visitors can subscribe to be notified on launch day\n\n"
        "> [!warning] Do NOT put text on the banner image — PH guidelines prohibit it and text "
        "gets cropped on mobile.\n\n"
        "## Why It Matters\n\n"
        "1. Subscribers get a PH notification when you launch — these are your warmest early "
        "voters\n"
        "2. It builds a list of genuinely interested PH users (not random email addresses)\n"
        "3. Coming Soon subscribers tend to be active PH members whose votes carry weight\n"
        "4. You can share the Coming Soon link to gauge interest before committing to a date\n\n"
        "## Timing\n\n"
        "Set up the Coming Soon page **2-3 weeks** before launch. Promote it in relevant "
        "communities and social channels. Aim for **100+ subscribers** before setting your launch "
        "date."
    ),
    (
        "The Maker's Comment",
        "The Maker's Comment is the first comment on your product's PH page, posted by you (the "
        "maker) immediately after going live. It is arguably the most important piece of copy in "
        "your entire launch.\n\n"
        "## Why It Matters\n\n"
        "- It is the **first thing** people read after your tagline and description\n"
        "- It sets the tone for all subsequent discussion\n"
        "- A great maker's comment gets upvoted to the top, encouraging more engagement\n"
        "- It humanizes the product — people connect with makers, not companies\n\n"
        "## What to Include\n\n"
        "1. **Personal Story** — Why did you build this? What frustrated you? What gap did you see?\n"
        "2. **The Problem** — Be specific about who struggles with this and why existing solutions "
        "fall short.\n"
        "3. **Your Approach** — What makes your solution different? Not features, but philosophy.\n"
        "4. **Engagement Questions** — Ask 2-3 specific questions to encourage comments: 'What "
        "features would make this essential for your workflow?' or 'How do you currently solve "
        "this problem?'\n"
        "5. **PH-Exclusive Offer** — Give the community something special: extended trial, discount "
        "code, free tier upgrade, or early access to an upcoming feature.\n\n"
        "## What to Avoid\n\n"
        "- Marketing speak or corporate language\n"
        "- Feature lists (that is what the description and gallery are for)\n"
        "- Asking for upvotes (against PH rules and triggers anti-gaming)\n"
        "- Being too long — aim for **150-250 words**"
    ),
    (
        "Why Timing Matters",
        "The timing of your Product Hunt launch has a measurable impact on results. The PH "
        "community's behavior follows predictable patterns.\n\n"
        "## Best Days to Launch\n\n"
        "- **Tuesday, Wednesday, Thursday** — highest active user counts, most engagement\n"
        "- Tuesday is generally considered the best single day\n\n"
        "## Worst Days\n\n"
        "- **Friday** — community activity drops as the weekend approaches\n"
        "- **Saturday/Sunday** — lowest traffic, fewest active users\n"
        "- **Monday** — people are catching up on work, not browsing PH\n\n"
        "## Launch Time\n\n"
        "> [!tip] Always launch at **12:01 AM Pacific Time**. This gives you the full 24-hour "
        "competitive window. Launching at noon means you only have 12 hours to accumulate votes.\n\n"
        "## Seasonal Avoidance\n\n"
        "- Major tech conferences (CES, WWDC, Google I/O) — attention is elsewhere\n"
        "- Major holidays (Thanksgiving week, Christmas-New Year, July 4th week)\n"
        "- Apple/Google product launch weeks — media is saturated\n"
        "- End of quarter — many companies launch simultaneously, increasing competition\n\n"
        "## Competition Check\n\n"
        "Before committing to a date, check the PH 'Coming Soon' section. If a well-known "
        "brand or heavily-followed product is launching the same day, consider shifting by a "
        "day or two."
    ),
    (
        "The 7 Phases Explained",
        "A successful Product Hunt launch is not a single event — it is a **7-phase operation** "
        "spanning 6+ weeks. Each phase builds on the previous one, and skipping a phase creates "
        "gaps that are nearly impossible to fix on launch day.\n\n"
        "## Phase 1: Foundation (4+ weeks before)\n\n"
        "Define your value proposition, target personas, and success metrics. Without these, "
        "every subsequent decision is guesswork. This phase also includes creating a PH-specific "
        "landing page and setting up analytics so you can measure results.\n\n"
        "## Phase 2: Community (3-4 weeks before)\n\n"
        "Build authentic presence on PH by engaging with other products. Recruit your Launch "
        "Squad of 50-100 supporters. Secure a hunter. This phase cannot be rushed — PH's "
        "algorithm can detect accounts that suddenly become active right before a launch.\n\n"
        "## Phase 3: Assets (2-3 weeks before)\n\n"
        "Create all visual and written assets: tagline, description, logo, gallery images, "
        "demo video, Maker's Comment, FAQ answers, social media graphics, and your PH-exclusive "
        "offer. Quality here directly impacts conversion.\n\n"
        "## Phase 4: Pre-Launch (1-2 weeks before)\n\n"
        "Set up the Coming Soon page, schedule the launch, brief your squad, prepare your "
        "staggered outreach schedule, and test your onboarding flow for PH visitors. Remove "
        "any friction (paywalls, credit card gates) that would cause bounces.\n\n"
        "## Phase 5: Launch Day (Day 0)\n\n"
        "Execute the plan: verify the launch, post Maker's Comment, activate waves of outreach "
        "throughout the day, respond to every comment within 15 minutes, and track metrics "
        "in real time. This is a full 24-hour operation requiring team shifts.\n\n"
        "## Phase 6: Post-Launch (Days 1-7)\n\n"
        "Thank the community, share results on social media, write a retrospective, follow up "
        "with engaged commenters, fix issues surfaced in feedback, and nurture new signups.\n\n"
        "## Phase 7: Leverage (Weeks 2-4)\n\n"
        "Convert launch momentum into lasting value: pitch PR using your ranking as proof, "
        "create backlink campaigns, repurpose assets, spotlight power users, and submit to "
        "listing directories. Plan your re-launch for the next major update."
    ),
    (
        "What Top 5 Actually Takes",
        "Many teams underestimate the effort required for a top Product Hunt ranking. Here are "
        "realistic benchmarks based on analysis of hundreds of launches.\n\n"
        "## Benchmarks by Ranking Tier\n\n"
        "### #1 Product of the Day\n\n"
        "- **600-1200+ upvotes** (varies greatly by competition)\n"
        "- 100-300+ comments with genuine discussion\n"
        "- Strong engagement velocity throughout the full 24 hours\n"
        "- Usually requires a hunter with large following OR exceptional viral organic reach\n\n"
        "### #2-#3 Product of the Day\n\n"
        "- **400-800 upvotes**\n"
        "- 60-150 comments\n"
        "- Steady engagement, can afford some lulls\n\n"
        "### #4-#5 Product of the Day\n\n"
        "- **250-500 upvotes**\n"
        "- 30-80 comments\n"
        "- Achievable with a well-executed plan and moderate network\n\n"
        "### Top 10 (still valuable)\n\n"
        "- **150-300 upvotes**\n"
        "- 15-40 comments\n"
        "- Realistic for most startups with basic preparation\n\n"
        "## Important Caveats\n\n"
        "> [!info] These numbers vary dramatically by day. A Wednesday with several strong launches "
        "requires more than a quiet Tuesday.\n\n"
        "- Vote quality matters more than count — 200 votes from established members can "
        "outrank 400 votes from new accounts.\n"
        "- Comments and engagement depth are weighted heavily."
    ),
    (
        "Common Mistakes That Kill Launches",
        "These are the 8 most frequent mistakes that derail Product Hunt launches. Each one is "
        "preventable with proper preparation.\n\n"
        "## 1. Launching Without a Squad\n\n"
        "Going live with zero prepared supporters means relying entirely on organic PH discovery. "
        "The algorithm rewards early velocity, so starting from zero means you never build "
        "momentum.\n\n"
        "## 2. Asking People to 'Upvote'\n\n"
        "> [!warning] Directly soliciting upvotes violates PH community norms and can trigger "
        "anti-gaming penalties. Instead, ask people to 'check it out and share their thoughts.'\n\n"
        "## 3. Launching on Friday or Weekend\n\n"
        "Community engagement drops significantly. You are competing for a smaller pool of "
        "attention with the same effort.\n\n"
        "## 4. Poor Maker's Comment\n\n"
        "A missing, late, or corporate-sounding Maker's Comment kills the human connection that "
        "drives engagement. Write it in advance, make it personal, post within 5 minutes.\n\n"
        "## 5. No PH-Specific Landing Page\n\n"
        "Sending PH visitors to your generic homepage with no mention of PH means they do not "
        "feel special and convert at a fraction of the rate.\n\n"
        "## 6. Credit Card Walls\n\n"
        "PH visitors are curious explorers, not committed buyers. Any friction in the first 2 "
        "minutes causes immediate bounces. Remove payment requirements for PH traffic.\n\n"
        "## 7. Going Silent After Launch\n\n"
        "Not responding to comments quickly, not posting updates, and not engaging with the "
        "community after day 1 wastes the relationship capital built during the launch.\n\n"
        "## 8. Treating It as a One-Day Event\n\n"
        "The launch day is phase 5 of 7. Without the 4 weeks of preparation before and the "
        "3 weeks of leverage after, you capture a fraction of the potential value."
    ),
    (
        "Neutron GTM Gaps",
        "Analysis of what was missing from the original Neutron GTM spreadsheet approach and why "
        "a structured 7-phase system is necessary.\n\n"
        "## The 10 Critical Gaps\n\n"
        "### 1. No Algorithm Awareness\n\n"
        "The spreadsheet treated all votes as equal and did not "
        "account for vote quality, velocity patterns, or anti-gaming measures.\n\n"
        "### 2. Missing Community Phase\n\n"
        "No time allocated for building authentic PH presence "
        "before launch. You cannot fake 3 weeks of engagement history.\n\n"
        "### 3. No Hunter Strategy\n\n"
        "The role of hunters, their follower-based distribution, and "
        "the 2-3 week outreach timeline were not included.\n\n"
        "### 4. Undifferentiated Outreach\n\n"
        "All supporters were contacted at once instead of in "
        "staggered waves. This creates a spike-then-silence pattern that the algorithm penalizes.\n\n"
        "### 5. No Coming Soon Page\n\n"
        "Pre-launch follower collection was skipped, losing the "
        "warmest possible audience for launch day.\n\n"
        "### 6. Maker's Comment as Afterthought\n\n"
        "The most important piece of launch copy was not "
        "planned, drafted, or reviewed in advance.\n\n"
        "### 7. No Post-Launch Plan\n\n"
        "Everything stopped after launch day. The 3 weeks of leverage "
        "and amplification that multiply the launch's value were completely absent.\n\n"
        "### 8. Asset Quality Bar Too Low\n\n"
        "No specifications for image sizes, video length, tagline "
        "character limits, or mobile optimization requirements.\n\n"
        "### 9. No Timing Strategy\n\n"
        "Launch day and time were arbitrary rather than data-driven. "
        "No competitive analysis of what else was launching.\n\n"
        "### 10. No Success Metrics\n\n"
        "Without defined targets (upvote goals, comment benchmarks, "
        "conversion rates), there was no way to measure success or adjust tactics during the "
        "launch."
    ),
]
# fmt: on
